name: stand
description: A new Flutter project.
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  permission_handler: ^10.3.0
  get_storage: ^2.1.1
  geolocator: ^9.0.2
  flutter_localizations:
    sdk: flutter
  intl: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.11
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appicon.png"
  min_sdk_android: 19

flutter:
  generate: true
  uses-material-design: true